// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdubigQfnNLwkBgJsELYX0vKuTjDsAadA',
    appId: '1:101606187066:web:f3eec72eb8e3f84bac5503',
    messagingSenderId: '101606187066',
    projectId: 'chat-app-90123',
    authDomain: 'chat-app-90123.firebaseapp.com',
    storageBucket: 'chat-app-90123.appspot.com',
    measurementId: 'G-8L018GJG6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7LzN5jaVra5vyloE6K7hMjhcNrP6Ty9k',
    appId: '1:101606187066:android:ea7d0f99dc9a72f2ac5503',
    messagingSenderId: '101606187066',
    projectId: 'chat-app-90123',
    storageBucket: 'chat-app-90123.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdubigQfnNLwkBgJsELYX0vKuTjDsAadA',
    appId: '1:101606187066:web:c33646f5eb59ab4aac5503',
    messagingSenderId: '101606187066',
    projectId: 'chat-app-90123',
    authDomain: 'chat-app-90123.firebaseapp.com',
    storageBucket: 'chat-app-90123.appspot.com',
    measurementId: 'G-TTMP9B03QN',
  );
}
